export interface SugerenciaPregunta {
  id: string;
  keyTraducida: string; // Enlace limpio con el JSON
  modo: 'FUSEKI' | 'DBPEDIA_ONLINE' | 'DBPEDIA_OFFLINE';
  query: string;
}

const PREFIX_FUSEKI = `PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ont: <http://www.semanticweb.org/dell/ontologies/2026/2#>
`;

export const LISTA_SUGERENCIAS: SugerenciaPregunta[] = [
  { id: "p1", keyTraducida: "preguntas.p1", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?nombreDirector ?tituloEpisodio WHERE { ?episodio ont:episodioDirigidoPor ?director . ?episodio ont:nombreEpisodio ?tituloEpisodio . ?director ont:nombreDirector ?nombreDirector . ?director ont:reconocido ?esRenombrado . FILTER (STR(?esRenombrado) = "si") }` },
  { id: "p2", keyTraducida: "preguntas.p2", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?nombreDelActor ?nombreDelPremio WHERE { ?actor ont:premioActor ?premio . ?actor ont:actorInterpretadoPor ?nombreDelActor . ?premio ont:nombrePremio ?nombreDelPremio . }` },
  { id: "p3", keyTraducida: "preguntas.p3", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT DISTINCT ?nombreSerie ?nombreDelPersonaje WHERE { ?temporada ont:perteneceASerie ?serie . ?serie ont:tituloSerie ?nombreSerie . ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:salePersonaje ?personaje . ?personaje ont:rolNarrativo ?rol . FILTER (REGEX(STR(?rol), "secundario", "i")) ?personaje ont:nombrePersonage ?nombreDelPersonaje . } ORDER BY ?nombreSerie` },
  { id: "p4", keyTraducida: "preguntas.p4", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT DISTINCT ?nombreSerie ?nombreActorYPersonaje ?nombreEpisodio WHERE { ?temporada ont:perteneceASerie ?serie . ?serie ont:tituloSerie ?nombreSerie . ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:nombreEpisodio ?nombreEpisodio . ?episodio ont:salePersonaje ?personaje . ?personaje ont:esInterpretadoPor ?actor . ?personaje ont:nombrePersonage ?nombrePers . ?actor ont:actorInterpretadoPor ?nombreAct . FILTER (STR(?nombrePers) = STR(?nombreAct)) BIND(STR(?nombreAct) AS ?nombreActorYPersonaje) } ORDER BY ?nombreSerie` },
  { id: "p5", keyTraducida: "preguntas.p5", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT DISTINCT ?nombreSerie ?nombreEpisodio WHERE { ?temporada ont:perteneceASerie ?serie . ?serie ont:tituloSerie ?nombreSerie . ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:nombreEpisodio ?nombreEpisodio . ?episodio ont:observacion ?detalleObservacion . FILTER (REGEX(STR(?detalleObservacion), "muerte protagonista", "i")) } ORDER BY ?nombreSerie` },
  { id: "p6", keyTraducida: "preguntas.p6", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?tituloDeLaSerie ?observacionRemake WHERE { ?temporada ont:perteneceASerie ?serie . ?serie ont:tituloSerie ?tituloDeLaSerie . ?serie ont:detalleSerie ?observacionRemake . FILTER (REGEX(STR(?observacionRemake), "remake", "i")) }` },
  { id: "p7", keyTraducida: "preguntas.p7", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?serie ?nombreEpisodio ?estado WHERE { ?temporada ont:perteneceASerie ?serie . ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:nombreEpisodio ?nombreEpisodio . ?episodio ont:observacion ?estado . FILTER (REGEX(STR(?nombreEpisodio), "Pilot", "i")) FILTER (REGEX(STR(?estado), "modificado|rehecho", "i")) }` },
  { id: "p8", keyTraducida: "preguntas.p8", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?serie1 ?fecha1 ?serie2 ?fecha2 WHERE { ?serie1 rdf:type ont:Series_televisivas . ?serie2 rdf:type ont:Series_televisivas . ?serie1 ont:fechaEstreno ?fecha1 . ?serie2 ont:fechaEstreno ?fecha2 . FILTER (?serie1 != ?serie2) FILTER (STR(?serie1) < STR(?serie2)) FILTER (REGEX(STR(?fecha1), ".*-01-20T00:00:00.*") && REGEX(STR(?fecha2), ".*-01-20T00:00:00.*")) FILTER (STR(?fecha1) != STR(?fecha2)) } ORDER BY ?fecha1` },
  { id: "p9", keyTraducida: "preguntas.p9", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?nombreDelPersonaje ?actorInterpretado WHERE { ?personaje ont:rolNarrativo ?rol . FILTER (REGEX(STR(?rol), "Protagonista", "i")) ?personaje ont:nombrePersonage ?nombreDelPersonaje . ?personaje ont:esInterpretadoPor ?actorInterpretado . }` },
  { id: "p10", keyTraducida: "preguntas.p10", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT DISTINCT ?nombreTemporada ?nombreDelPersonaje WHERE { ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:salePersonaje ?personaje . ?personaje ont:nombrePersonage ?nombreDelPersonaje . BIND(STR(?temporada) AS ?nombreTemporada) } ORDER BY ?nombreTemporada` },
  { id: "p11", keyTraducida: "preguntas.p11", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT DISTINCT ?nombreTemporada ?nombreDelPersonaje ?nombreActor WHERE { ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:salePersonaje ?personaje . ?personaje ont:nombrePersonage ?nombreDelPersonaje . ?personaje ont:esInterpretadoPor ?actor . ?actor ont:actorInterpretadoPor ?nombreActor . BIND(STR(?temporada) AS ?nombreTemporada) } ORDER BY ?nombreTemporada` },
  { id: "p12", keyTraducida: "preguntas.p12", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?personaje (COUNT(?actor) AS ?numeroDeActores) WHERE { ?personaje ont:esInterpretadoPor ?actor . } GROUP BY ?personaje HAVING (COUNT(?actor) > 1)` },
  { id: "p13", keyTraducida: "preguntas.p13", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?serie ?fecha ?genero WHERE { ?serie ont:tieneGenero ont:Genero_Ciencia_Ficcion . ?serie ont:tieneGenero ?genero . ?serie ont:fechaEstreno ?fecha . FILTER (STR(?fecha) > "2015") } ORDER BY ?fecha` },
  { id: "p14", keyTraducida: "preguntas.p14", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?genero (AVG(?duracion) AS ?promedioDuracion) WHERE { ?serie ont:tieneGenero ?genero . ?temporada ont:perteneceASerie ?serie . ?temporada ont:tieneEpisodios ?episodio . ?episodio ont:duracionMinutos ?duracion . } GROUP BY ?genero ORDER BY DESC(?promedioDuracion) LIMIT 1` },
  { id: "p15", keyTraducida: "preguntas.p15", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?serie (COUNT(?genero) AS ?totalGeneros) (GROUP_CONCAT(?genero; separator=", ") AS ?listaGeneros) WHERE { ?serie ont:tieneGenero ?genero . } GROUP BY ?serie HAVING (COUNT(?genero) >= 3)` },
  { id: "p16", keyTraducida: "preguntas.p16", modo: "FUSEKI", query: PREFIX_FUSEKI + `SELECT ?subgenero (COUNT(?serie) AS ?cantidadSeries) WHERE { ?serie ont:tieneGenero ?instanciaGenero . ?instanciaGenero ont:subGenero ?subgenero . } GROUP BY ?subgenero ORDER BY DESC(?cantidadSeries)` }
];